# Author: Daniel Ortiz Mart\'inez
# *- bash -*

# Gets the system translations that are generated by a CAT system from
# the output file of thot_cat_using_client

if [ $# -ne 1 ]; then
    echo "Usage: thot_get_sys_trans <thot_cat_using_client_output>"
else

    file=$1
    ${GREP} "<reference>" -A 1 ${file} | ${GREP} "<hyp" | \
        ${AWK} -v n=$1 '{
                                for(i=3;i<=NF-1;++i)
                                {
                                  if(i==NF-1) printf"%s",$(NF-1)
                                  else printf"%s ",$i
                                }
                                printf"\n"
                              }' | ${SED} -e s"/^\^//g"
fi
