# Author: Daniel Ortiz Mart\'inez
# *- bash -*

# merge the counts of a seglentable generated by thot

if [ $# -ne 0 -a $# -ne 1 ]; then
echo "Usage: thot_merge_seglen_counts"
else

${AWK}   '{
            if(!(($1,$2) in counts))
            {
              counts[$1,$2]=$3
            }
            else
            {
              counts[$1,$2]+=$3
            }
          }
       END{
            for( entry in counts)
            {
              split(entry, entryArr, "\034")
              printf("%d %d %d\n",entryArr[1],entryArr[2],counts[entryArr[1],entryArr[2]]); 
            }
          }' $1

fi
